// Anonymous Guest identity.
//
// The single security rule this module exists to enforce: a Guest session id
// is generated by the server and travels only in an HttpOnly cookie. It is
// never read from a URL, query string, request body, or custom header, so a
// client cannot name someone else's session. Everything downstream scopes on
// the value returned by `readGuestSessionId` and nothing else.
//
// This is anonymous Guest identity only — not an account system. It proves
// "these requests are the same visitor", never "this visitor is anyone".

/** Cookie carrying the Guest session id. */
export const GUEST_COOKIE_NAME = 'wtlab_guest';

/** 32 bytes → 64 hex chars → 256 bits of entropy, not enumerable. */
const SESSION_ID_BYTES = 32;
const SESSION_ID_PATTERN = /^[0-9a-f]{64}$/;

/**
 * Prototype cookie lifetime. Deliberately not the final retention policy —
 * TTL is a deferred decision (see ADR-0004); this only bounds the cookie so a
 * forgotten browser tab does not hold an identity indefinitely.
 */
export const PROTOTYPE_COOKIE_MAX_AGE_SECONDS = 60 * 60 * 12;

/** Server-side generation. Never accept an id the client proposes. */
export function createGuestSessionId(): string {
	const bytes = new Uint8Array(SESSION_ID_BYTES);
	crypto.getRandomValues(bytes);
	return Array.from(bytes, (byte) => byte.toString(16).padStart(2, '0')).join('');
}

export function isGuestSessionId(value: string): boolean {
	return SESSION_ID_PATTERN.test(value);
}

/**
 * The ONLY trusted source of Guest identity. Reads the cookie header and
 * returns the session id when one is present and well-formed.
 *
 * A malformed or absent cookie yields null — the caller then mints a fresh
 * identity rather than trusting anything else on the request.
 */
export function readGuestSessionId(cookieHeader: string | null | undefined): string | null {
	if (!cookieHeader) return null;

	for (const part of cookieHeader.split(';')) {
		const separator = part.indexOf('=');
		if (separator === -1) continue;
		const name = part.slice(0, separator).trim();
		if (name !== GUEST_COOKIE_NAME) continue;
		const value = part.slice(separator + 1).trim();
		return isGuestSessionId(value) ? value : null;
	}

	return null;
}

/**
 * Set-Cookie for a Guest identity.
 *
 * HttpOnly keeps it out of reach of page scripts (so it cannot be read,
 * copied into a request, or forged from the client). SameSite=Lax lets it
 * ride ordinary same-site navigation — which is what makes a second tab
 * resolve to the same workspace without any cross-tab messaging.
 */
export function guestSessionCookie(
	sessionId: string,
	options?: { secure?: boolean; maxAgeSeconds?: number }
): string {
	const maxAge = options?.maxAgeSeconds ?? PROTOTYPE_COOKIE_MAX_AGE_SECONDS;
	const attributes = [
		`${GUEST_COOKIE_NAME}=${sessionId}`,
		'Path=/',
		'HttpOnly',
		'SameSite=Lax',
		`Max-Age=${maxAge}`,
	];
	// Secure is omitted on plain-HTTP localhost only, where the browser would
	// otherwise drop the cookie and local verification could not run.
	if (options?.secure !== false) attributes.push('Secure');
	return attributes.join('; ');
}

/** Expires the cookie — used when a Guest ends their own session. */
export function clearedGuestSessionCookie(options?: { secure?: boolean }): string {
	const attributes = [`${GUEST_COOKIE_NAME}=`, 'Path=/', 'HttpOnly', 'SameSite=Lax', 'Max-Age=0'];
	if (options?.secure !== false) attributes.push('Secure');
	return attributes.join('; ');
}
