import type { CsvTemplateDefinition } from '../../../../platform/templates/types.ts';

export const supplierDependencyAdvancedTemplate: CsvTemplateDefinition = {
	templateId: 'supplier-dependency-advanced-input',
	instrumentId: 'supplier-dependency-radar',
	modeId: 'advanced',
	version: '1',
	filename: 'supplier-dependency-advanced-input.csv',
	description: 'One row per supplier-material relationship. Blank optional fields mean unknown. Reusable: download, edit, re-upload.',
	columns: [
		{ id: 'supplierName', required: true, sample: 'example-supplier-a' },
		{ id: 'materialName', required: true, sample: 'example-material-1' },
		{ id: 'materialCategory', required: false, sample: 'resin' },
		{ id: 'supplierSharePercent', required: false, sample: '70' },
		{ id: 'criticalMaterial', required: false, sample: 'true' },
		{ id: 'singleSource', required: false, sample: 'true' },
		{ id: 'alternativeSupplierAvailable', required: false, sample: 'true' },
		{ id: 'qualifiedAlternativeAvailable', required: false, sample: 'false' },
		{ id: 'qualificationRequired', required: false, sample: 'true' },
		{ id: 'qualificationLeadTimeMonths', required: false, sample: '9' },
		{ id: 'customerApprovalRequired', required: false, sample: 'true' },
		{ id: 'trialProductionRequired', required: false, sample: 'false' },
		{ id: 'leadTimeDays', required: false, sample: '45' },
		{ id: 'averageDelayDays', required: false, sample: '5' },
		{ id: 'deliveryReliabilityPercent', required: false, sample: '92' },
		{ id: 'agreementCancellationCount', required: false, sample: '0' },
		{ id: 'annualUsage', required: false, sample: '1200' },
		{ id: 'annualExposureValue', required: false, sample: '250000' },
		{ id: 'optionalNotes', required: false, sample: '' },
	],
	sampleRows: [
		{
			supplierName: 'example-supplier-a',
			materialName: 'example-material-1',
			materialCategory: 'resin',
			supplierSharePercent: '70',
			criticalMaterial: 'true',
			singleSource: 'true',
			alternativeSupplierAvailable: 'true',
			qualifiedAlternativeAvailable: 'false',
			qualificationRequired: 'true',
			qualificationLeadTimeMonths: '9',
			customerApprovalRequired: 'true',
			trialProductionRequired: 'false',
			leadTimeDays: '45',
			averageDelayDays: '5',
			deliveryReliabilityPercent: '92',
			agreementCancellationCount: '0',
			annualUsage: '1200',
			annualExposureValue: '250000',
			optionalNotes: '',
		},
		{
			supplierName: 'example-supplier-b',
			materialName: 'example-material-2',
			materialCategory: 'packaging',
			supplierSharePercent: '40',
			criticalMaterial: 'false',
			singleSource: 'false',
			alternativeSupplierAvailable: 'true',
			qualifiedAlternativeAvailable: 'true',
			qualificationRequired: 'false',
			qualificationLeadTimeMonths: '',
			customerApprovalRequired: 'false',
			trialProductionRequired: 'false',
			leadTimeDays: '20',
			averageDelayDays: '1',
			deliveryReliabilityPercent: '98',
			agreementCancellationCount: '0',
			annualUsage: '5000',
			annualExposureValue: '30000',
			optionalNotes: '',
		},
		{
			supplierName: 'example-supplier-a',
			materialName: 'example-material-3',
			materialCategory: 'resin',
			supplierSharePercent: '100',
			criticalMaterial: 'true',
			singleSource: 'true',
			alternativeSupplierAvailable: 'false',
			qualifiedAlternativeAvailable: '',
			qualificationRequired: 'true',
			qualificationLeadTimeMonths: '',
			customerApprovalRequired: 'true',
			trialProductionRequired: 'true',
			leadTimeDays: '60',
			averageDelayDays: '',
			deliveryReliabilityPercent: '',
			agreementCancellationCount: '',
			annualUsage: '400',
			annualExposureValue: '180000',
			optionalNotes: 'formula-locked',
		},
	],
};
