// Instrument catalog data. Registry-driven pages render from this list —
// no page hardcodes instrument metadata. Only water-level-checker is
// implemented today; the rest are known in the product architecture but
// not yet usable, and their entries must say so honestly.

import type { InstrumentEntry } from './catalog';

export const instruments: readonly InstrumentEntry[] = [
	{
		id: 'inventory-buffer-check',
		slug: 'water-level-checker',
		displayName: 'Water Level Checker',
		shortName: 'Water Level',
		description:
			'Quickly check whether current inventory can cover consumption, replenishment lead time, and safety buffer.',
		layer: 'observe',
		category: 'supply-chain-inventory',
		status: 'available',
		enabled: true,
		// Confirmed decision: the live route stays /tools/inventory-buffer-check.
		route: '/tools/inventory-buffer-check',
		version: '0.2',
		coreQuestion: 'Is current inventory sufficient to cover replenishment lead time and safety buffer?',
		capabilities: ['manual-input', 'csv-import', 'calculate', 'export'],
		dataPersistence: 'none',
		exportFormats: ['csv', 'json'],
		implementationState: 'implemented',
		toolId: 'inventory-buffer-check',
		prototypeRefs: ['021-WTLab Water Level Checker Result v1(standalone).html'],
	},
	{
		id: 'arrival-collision-detector',
		slug: 'arrival-collision-detector',
		displayName: 'Arrival Collision Detector',
		shortName: 'Arrival Collision',
		description: 'Detect incoming shipments that land too close together or overload a single period.',
		layer: 'observe',
		category: 'supply-chain-inventory',
		status: 'beta',
		enabled: true,
		route: '/instruments/arrival-collision-detector',
		version: '0.1',
		coreQuestion: 'Will any expected arrivals collide with each other in the same period?',
		capabilities: ['manual-input', 'csv-import', 'calculate', 'export'],
		dataPersistence: 'none',
		exportFormats: ['csv'],
		implementationState: 'implemented',
		toolId: 'arrival-collision-detector',
		prototypeRefs: ['022-WTLab Arrival Collision Detector v1(standalone).html'],
	},
	{
		id: 'demand-wave-radar',
		slug: 'demand-wave-radar',
		displayName: 'Demand Wave Radar',
		shortName: 'Demand Wave',
		description: 'Spot acceleration or deceleration in consumption before it breaks the replenishment rhythm.',
		layer: 'observe',
		category: 'supply-chain-inventory',
		status: 'prototype',
		enabled: false,
		route: '/instruments/demand-wave-radar',
		version: '0.0.1',
		coreQuestion: 'Is demand accelerating beyond what the current buffer assumptions were built for?',
		capabilities: ['manual-input', 'calculate'],
		dataPersistence: 'none',
		exportFormats: [],
		implementationState: 'placeholder',
		prototypeRefs: ['023-WTLab Demand Wave Radar (Standalone).html'],
	},
	{
		id: 'dead-stock-scanner',
		slug: 'dead-stock-scanner',
		displayName: 'Dead Stock Scanner',
		shortName: 'Dead Stock',
		description: 'Surface inventory that has stopped moving and quantify how much capital it locks up.',
		layer: 'observe',
		category: 'supply-chain-inventory',
		status: 'prototype',
		enabled: false,
		route: '/instruments/dead-stock-scanner',
		version: '0.0.1',
		coreQuestion: 'Which items have stopped moving, and how much capital do they tie up?',
		capabilities: ['csv-import', 'calculate'],
		dataPersistence: 'none',
		exportFormats: [],
		implementationState: 'placeholder',
		prototypeRefs: ['024-WTLab Dead Stock Scanner.html'],
	},
	{
		id: 'lead-time-gap-checker',
		slug: 'lead-time-gap-checker',
		displayName: 'Lead Time Gap Checker',
		shortName: 'Lead Time Gap',
		description: 'Compare assumed replenishment lead times against observed reality and flag drift.',
		layer: 'observe',
		category: 'supply-chain-inventory',
		status: 'prototype',
		enabled: false,
		route: '/instruments/lead-time-gap-checker',
		version: '0.0.1',
		coreQuestion: 'Are the lead times we plan with still the lead times we actually get?',
		capabilities: ['manual-input', 'calculate'],
		dataPersistence: 'none',
		exportFormats: [],
		implementationState: 'placeholder',
		prototypeRefs: ['025-WTLab Lead Time Gap Checker.html'],
	},
	{
		id: 'supplier-dependency-radar',
		slug: 'supplier-dependency-radar',
		displayName: 'Supplier Dependency Radar',
		shortName: 'Supplier Dependency',
		description: 'Map how concentrated critical supply is on single suppliers, regions, or routes.',
		layer: 'think',
		category: 'supply-chain-risk',
		status: 'prototype',
		enabled: false,
		route: '/instruments/supplier-dependency-radar',
		version: '0.0.1',
		coreQuestion: 'Where does a single supplier failure take the whole operation down with it?',
		capabilities: ['manual-input', 'calculate'],
		dataPersistence: 'none',
		exportFormats: [],
		implementationState: 'placeholder',
		prototypeRefs: ['026-WTLab Supplier Dependency Radar - Standalone.html'],
	},
	{
		id: 'buffer-drift-monitor',
		slug: 'buffer-drift-monitor',
		displayName: 'Buffer Drift Monitor',
		shortName: 'Buffer Drift',
		description: 'Track how actual safety buffers drift away from their intended levels over time.',
		layer: 'observe',
		category: 'supply-chain-inventory',
		status: 'prototype',
		enabled: false,
		route: '/instruments/buffer-drift-monitor',
		version: '0.0.1',
		coreQuestion: 'Are our safety buffers still the size we decided they should be?',
		capabilities: ['manual-input', 'calculate'],
		dataPersistence: 'none',
		exportFormats: [],
		implementationState: 'placeholder',
		prototypeRefs: ['027-WTLab Buffer Drift Monitor.html'],
	},
];
