// Workspace catalog data. Workspaces organize records, entities,
// observations, and decisions — they are platform surfaces, not
// instruments, and are never listed in the Instrument Library.

import type { ContinuityAction, WorkspaceEntry } from './catalog';

export const workspaces: readonly WorkspaceEntry[] = [
	{
		id: 'command-center',
		slug: 'command-center',
		displayName: 'Operational Command Center',
		description: 'Routes active work: today’s reviews, pending decisions, and the current operational focus.',
		layer: 'platform',
		status: 'prototype',
		enabled: true,
		// Confirmed decision: the root route keeps the minimal homepage;
		// the Command Center lives at /command instead of /.
		route: '/command',
		coreQuestion: 'What needs my attention right now?',
		implementationState: 'partial',
		prototypeRefs: ['010-WTLab platform architecture v3.html'],
	},
	{
		id: 'continuity-center',
		slug: 'continuity-center',
		displayName: 'Continuity Center',
		description: 'Preserves and transfers user work: save, export, email copy, re-import, AI handoff.',
		layer: 'continue',
		status: 'prototype',
		enabled: true,
		route: '/continuity',
		coreQuestion: 'How does my work survive beyond this browser tab?',
		implementationState: 'partial',
		prototypeRefs: [],
	},
	{
		id: 'data-intake',
		slug: 'data-intake',
		displayName: 'Data Intake Workspace',
		description: 'Bring operational data into WTLab: CSV import, normalization, and validation.',
		layer: 'work',
		status: 'prototype',
		enabled: false,
		route: '/workspace/data-intake',
		coreQuestion: 'How does raw operational data become something instruments can read?',
		implementationState: 'placeholder',
		prototypeRefs: ['030-WTLab Data Intake Workspace.html'],
	},
	{
		id: 'entity',
		slug: 'entity',
		displayName: 'Entity Workspace',
		description: 'Organize the materials, products, suppliers, and sites that observations attach to.',
		layer: 'work',
		status: 'prototype',
		enabled: false,
		route: '/workspace/entity',
		coreQuestion: 'What are the things we are actually tracking?',
		implementationState: 'placeholder',
		prototypeRefs: [],
	},
	{
		id: 'decision-priority',
		slug: 'decision-priority',
		displayName: 'Decision Priority Map',
		description: 'Rank open decisions by urgency and impact so review effort goes where it matters.',
		layer: 'think',
		status: 'prototype',
		enabled: false,
		route: '/workspace/decision-priority',
		coreQuestion: 'Which decision deserves attention first?',
		implementationState: 'placeholder',
		prototypeRefs: [],
	},
	{
		id: 'decision-memory',
		slug: 'decision-memory',
		displayName: 'Decision Memory',
		description: 'Keep the record of what was decided, on what evidence, and what would change it.',
		layer: 'continue',
		status: 'prototype',
		enabled: false,
		route: '/workspace/decision-memory',
		coreQuestion: 'Why did we decide this, and does that reasoning still hold?',
		implementationState: 'placeholder',
		prototypeRefs: [],
	},
	{
		id: 'relationship-explorer',
		slug: 'relationship-explorer',
		displayName: 'Operational Relationship Explorer',
		description: 'Explore how entities, observations, and decisions connect to each other.',
		layer: 'think',
		status: 'prototype',
		enabled: false,
		route: '/workspace/relationship-explorer',
		coreQuestion: 'What else does this observation or decision touch?',
		implementationState: 'placeholder',
		prototypeRefs: [],
	},
	{
		id: 'case-intelligence',
		slug: 'case-intelligence',
		displayName: 'Case Intelligence Workspace',
		description: 'Build reviewable cases from observations, hypotheses, and outcomes over time.',
		layer: 'think',
		status: 'prototype',
		enabled: false,
		route: '/workspace/case-intelligence',
		coreQuestion: 'What story does the accumulated evidence actually tell?',
		implementationState: 'placeholder',
		prototypeRefs: [],
	},
];

// Continuity capabilities — deliberately typed and surfaced as planned.
// Product rule: user work must never depend only on browser cookies or
// local site data; these are the future ways work leaves the browser.
export const continuityActions: readonly ContinuityAction[] = [
	{
		id: 'save',
		label: 'Save',
		description: 'Persist the current working state as a portable package.',
		state: 'planned',
	},
	{
		id: 'export',
		label: 'Export',
		description: 'Download results in an open format (CSV / JSON).',
		state: 'planned',
	},
	{
		id: 'email-copy',
		label: 'Email Copy',
		description: 'Send a copy of the current results to your own inbox.',
		state: 'planned',
	},
	{
		id: 're-import',
		label: 'Re-import',
		description: 'Load a previously exported package back into WTLab.',
		state: 'planned',
	},
	{
		id: 'ai-handoff',
		label: 'Prepare for AI',
		description: 'Package current context so an AI assistant can continue the analysis.',
		state: 'planned',
	},
];
